name: flutter_daemon
description: A programmable interface around the Flutter daemon protocol.
version: 1.0.0
repository: https://github.com/wolfenrain/flutter_daemon
issue_tracker: https://github.com/wolfenrain/flutter_daemon/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  process: ^4.2.4

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^4.0.0
